apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
 name: {{ .Release.Name }}-mongodb
spec:
  selector:
    matchLabels:
      app: mongo
  serviceName: {{ .Release.Name }}-mongodb-sevice
  replicas: {{ .Values.database.mongo.replica }}
  template:
    metadata:
      labels:
        app: mongo
        role: database
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
       - name: mongo-pod
         image: mongo
         command:
           - mongod
           - "--replSet"
           - rs0
           - "--bind_ip"
           - 0.0.0.0
#           - "--smallFiles"
#           - "--noprealloc"
         ports:
           - containerPort: 27017
         volumeMounts:
           - name: {{ .Values.database.mongo.pvc.name }}
             mountPath: /data/db
       - name: mongo-sidecar
         image: cvallance/mongo-k8s-sidecar
         env:
           - name: MONGO_SIDECAR_POD_LABELS
             value: "role=mongo,environment=test"
  volumeClaimTemplates:
   - metadata:
       name: {{ .Values.database.mongo.pvc.name }}
     spec:
       accessModes:
         - {{ .Values.database.mongo.pv.accessModes }}
       resources:
         requests:
           storage: {{ .Values.database.mongo.pvc.size }}
       storageClassName: {{ .Values.database.mongo.pv.storageClass.name }}

